# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  sourceRef:
    kind: OCIRepository
    name: flux-system
  wait: true
  timeout: 3m0s
  interval: 30m0s
  retryInterval: 10s
  path: apps/podinfo
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: podinfo-spec
