ingress:
  enabled: true
  className: traefik
  hosts:
    - host: podinfo.lab.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
