# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: flux-system
  name: ${HELM_RELEASE_NAME}
spec:
  interval: 30m0s
  chart:
    spec:
      chart: ${HELM_CHART_NAME}
      version: ${HELM_CHART_VERSION}
      sourceRef:
        kind: HelmRepository
        name: ${HELM_REPO_NAME}
      interval: 30m0s
  targetNamespace: ${HELM_NAMESPACE_NAME}
  install:
    crds: CreateReplace
    remediation:
      retries: 3
    timeout: 1m
  upgrade:
    remediation:
      retries: 3
    timeout: 5m
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: ${HELM_RELEASE_NAME}-spec
      optional: true
      valuesKey: values